import { jsPDF } from "jspdf";
import { formatPopulation, formatTemperature, formatRisk } from "./formatters";

/* ── colour helpers ── */
const rgb = (hex) => {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return [r, g, b];
};
const ORANGE  = rgb("#f97316");
const TEAL    = rgb("#38bdf8");
const GREEN   = rgb("#4ade80");
const RED     = rgb("#f43f5e");
const GREY    = [140, 140, 155];
const DARK    = [20, 22, 36];
const WHITE   = [255, 255, 255];
const BGLIGHT = [248, 249, 252];

const LEVEL_RGB = {
  extreme: rgb("#f43f5e"),
  high:    ORANGE,
  moderate:rgb("#fbbf24"),
  safe:    GREEN,
};

export function exportReport({ city, stats, hotspots, plan }) {
  const doc   = new jsPDF({ unit: "mm", format: "a4" });
  const W     = 210;
  const M     = 18;
  const INNER = W - M * 2;
  let y       = 0;

  /* ── helpers ── */
  const nl = (gap = 5) => { y += gap; };
  const newPage = () => { doc.addPage(); y = M; };
  const checkPage = (needed = 14) => { if (y + needed > 278) newPage(); };

  const hline = (yy, color = GREY, alpha = 0.3) => {
    doc.setDrawColor(...color);
    doc.setLineWidth(0.3);
    doc.line(M, yy, W - M, yy);
  };

  const fillRect = (x, yy, w, h, color) => {
    doc.setFillColor(...color);
    doc.rect(x, yy, w, h, "F");
  };

  const text = (str, x, yy, opts = {}) => {
    const { size = 10, color = DARK, bold = false, align = "left" } = opts;
    doc.setFontSize(size);
    doc.setTextColor(...color);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.text(String(str), x, yy, { align });
  };

  /* ════════════════════════════════════════════════
   * PAGE 1 — COVER + EXECUTIVE SUMMARY
   * ════════════════════════════════════════════════ */
  fillRect(0, 0, W, 52, DARK);

  // brand strip
  doc.setFillColor(249, 115, 22);
  doc.rect(0, 0, 5, 52, "F");

  text("THERMA", M + 6, 20, { size: 26, color: WHITE, bold: true });
  text("Urban Heat Mitigation Intelligence Platform", M + 6, 28, { size: 11, color: [200, 200, 210] });
  text("CITY PLANNING REPORT", M + 6, 36, { size: 9, color: ORANGE, bold: true });
  text(`${city.toUpperCase()}  ·  Generated ${new Date().toLocaleString()}`, M + 6, 43, { size: 9, color: GREY });

  y = 62;

  // exec summary header
  doc.setFillColor(249, 249, 252);
  doc.setDrawColor(230, 230, 235);
  doc.setLineWidth(0.3);
  doc.roundedRect(M, y, INNER, 6, 1, 1, "FD");
  text("EXECUTIVE SUMMARY", M + 4, y + 4.2, { size: 9, color: DARK, bold: true });
  y += 10;

  // stat boxes row
  const boxes = [
    { label: "Zones Mapped",    value: String(stats?.zonesMapped ?? 0),           color: TEAL },
    { label: "Critical Zones",  value: String(stats?.criticalZones ?? 0),         color: RED },
    { label: "People at Risk",  value: stats?.peopleAtRisk ?? "0K",               color: ORANGE },
    { label: "Avg Temperature", value: formatTemperature(stats?.avgTemperature ?? 0), color: ORANGE },
    { label: "Avg Risk Score",  value: `${formatRisk(stats?.avgRiskScore ?? 0)}/100`, color: RED },
    { label: "Budget",          value: `₹${(65 * 0.5).toFixed(1)}M`,             color: GREEN },
  ];

  const bw = (INNER - 5 * 4) / 6;
  boxes.forEach((b, i) => {
    const bx = M + i * (bw + 4);
    fillRect(bx, y, bw, 20, BGLIGHT);
    doc.setDrawColor(...b.color);
    doc.setLineWidth(0.4);
    doc.rect(bx, y, bw, 20);
    doc.setLineWidth(1.5);
    doc.line(bx, y, bx, y + 20);
    text(b.value, bx + bw / 2, y + 9, { size: 11, color: b.color, bold: true, align: "center" });
    text(b.label, bx + bw / 2, y + 15, { size: 7, color: GREY, align: "center" });
  });
  y += 26;

  // narrative summary
  const summaryLines = [
    `This report presents the urban heat mitigation plan for ${city} generated by the THERMA AI platform.`,
    `The analysis identified ${stats?.zonesMapped ?? 0} heat stress zones across the city, of which`,
    `${stats?.criticalZones ?? 0} are classified as EXTREME risk requiring immediate intervention.`,
    `A total of ${stats?.peopleAtRisk ?? "0K"} people are estimated to be at elevated heat stress risk.`,
  ];
  summaryLines.forEach(line => {
    checkPage(6);
    text(line, M, y, { size: 10, color: [60, 65, 80] });
    y += 5.5;
  });
  nl(6);

  // projected outcomes
  hline(y);
  nl(4);
  text("PROJECTED OUTCOMES AT 6 & 18 MONTHS", M, y, { size: 9, color: DARK, bold: true });
  nl(8);

  const outcomes = [
    ["Metric", "6-Month Projection", "18-Month Projection"],
    ["City-wide temp reduction", `−${(stats?.tempReduction ?? 2).toFixed(1)}°C`, `−${((stats?.tempReduction ?? 2) * 2.2).toFixed(1)}°C`],
    ["Population protected",     stats?.protectedPopulation ?? "0K",              `${Math.round((stats?.totalPopulation ?? 0) * 0.65)}K`],
    ["Zones remediated",         `${Math.round((stats?.zonesMapped ?? 0) * 0.4)}`,`${Math.round((stats?.zonesMapped ?? 0) * 0.85)}`],
    ["Estimated cost deployed",  `₹${(65 * 0.5 * 0.4).toFixed(1)}M`,            `₹${(65 * 0.5).toFixed(1)}M`],
  ];

  const colW = [70, 50, 50];
  outcomes.forEach((row, ri) => {
    checkPage(10);
    if (ri === 0) {
      fillRect(M, y - 3.5, INNER, 8, DARK);
      row.forEach((cell, ci) => {
        text(cell, M + colW.slice(0, ci).reduce((a, b) => a + b, 0) + 3, y + 1, { size: 9, color: WHITE, bold: true });
      });
    } else {
      if (ri % 2 === 0) fillRect(M, y - 3.5, INNER, 7, BGLIGHT);
      row.forEach((cell, ci) => {
        const cx = M + colW.slice(0, ci).reduce((a, b) => a + b, 0) + 3;
        text(cell, cx, y + 1, { size: 9, color: ci === 0 ? DARK : ci === 1 ? TEAL : GREEN });
      });
    }
    y += 8;
  });

  nl(8);

  /* ════════════════════════════════════════════════
   * PAGE 2 — TOP 5 PRIORITY ZONES
   * ════════════════════════════════════════════════ */
  newPage();

  fillRect(0, 0, W, 18, DARK);
  doc.setFillColor(249, 115, 22);
  doc.rect(0, 0, 5, 18, "F");
  text(`${city.toUpperCase()} — TOP PRIORITY INTERVENTION ZONES`, M + 6, 12, { size: 13, color: WHITE, bold: true });
  y = 28;

  const topZones = plan?.zonePlans?.slice(0, 5) ?? [];
  const topHotspots = [...(hotspots ?? [])].sort((a, b) => b.riskScore - a.riskScore).slice(0, 5);
  const zones = topZones.length > 0
    ? topZones.map(z => ({
        id:           z.zoneId,
        level:        z.level,
        temp:         z.currentTemp,
        risk:         z.riskScore,
        population:   z.population,
        intervention: z.interventionName,
        cost:         `₹${z.costCrore} Cr`,
        cooling:      `−${z.coolingImpactC}°C`,
        timeline:     `${z.timelineWeeksMin}–${z.timelineWeeksMax} wks`,
        driver:       z.dominantDriver ?? "Urban heat island",
      }))
    : topHotspots.map(h => ({
        id:           h.id,
        level:        h.level,
        temp:         h.temp,
        risk:         h.riskScore,
        population:   h.population,
        intervention: (h.intervention ?? "").replace(/_/g, " "),
        cost:         `₹${h.interventionCostCrore ?? "—"} Cr`,
        cooling:      `−${h.coolingImpactC ?? "—"}°C`,
        timeline:     h.timelineWeeksMin ? `${h.timelineWeeksMin}–${h.timelineWeeksMax} wks` : "—",
        driver:       h.dominantDriver ?? "Urban heat island",
      }));

  zones.forEach((z, i) => {
    checkPage(42);
    const levelColor = LEVEL_RGB[z.level] ?? ORANGE;
    // zone header band
    fillRect(M, y, INNER, 8, DARK);
    doc.setFillColor(...levelColor);
    doc.rect(M, y, 4, 8, "F");
    text(`#${i + 1}  ZONE ${z.id}`, M + 7, y + 5.5, { size: 10, color: WHITE, bold: true });
    text(z.level.toUpperCase(), W - M - 3, y + 5.5, { size: 9, color: levelColor, bold: true, align: "right" });
    y += 10;

    // zone stats row
    const zStats = [
      ["Temperature",  formatTemperature(z.temp)],
      ["Risk Score",   `${formatRisk(z.risk)}/100`],
      ["Population",   formatPopulation(z.population)],
      ["Intervention", z.intervention],
    ];
    const sw = INNER / 4;
    zStats.forEach(([label, val], si) => {
      const sx = M + si * sw;
      fillRect(sx + 0.5, y, sw - 1, 16, BGLIGHT);
      text(label, sx + 3, y + 6, { size: 8, color: GREY });
      text(val,   sx + 3, y + 13, { size: 9, color: DARK, bold: true });
    });
    y += 18;

    // intervention details row
    const iStats = [
      ["Est. Cost",         z.cost],
      ["Cooling Impact",    z.cooling],
      ["Timeline",          z.timeline],
      ["Heat Driver",       z.driver.slice(0, 28)],
    ];
    iStats.forEach(([label, val], si) => {
      const sx = M + si * sw;
      text(label, sx + 3, y + 5,  { size: 8, color: GREY });
      const valColor = si === 0 ? ORANGE : si === 1 ? GREEN : TEAL;
      text(val,   sx + 3, y + 11, { size: 9, color: si < 3 ? valColor : DARK });
    });
    y += 16;
    hline(y, GREY, 0.15);
    y += 4;
  });

  nl(4);

  /* ════════════════════════════════════════════════
   * PAGE 3 — BUDGET BREAKDOWN + RECOMMENDATIONS
   * ════════════════════════════════════════════════ */
  newPage();

  fillRect(0, 0, W, 18, DARK);
  doc.setFillColor(74, 222, 128);
  doc.rect(0, 0, 5, 18, "F");
  text("BUDGET ALLOCATION & RECOMMENDATIONS", M + 6, 12, { size: 13, color: WHITE, bold: true });
  y = 28;

  // budget breakdown
  text("INTERVENTION BUDGET BREAKDOWN", M, y, { size: 9, color: DARK, bold: true });
  nl(8);

  const alloc = plan?.budgetAllocation ?? {};
  const allocEntries = Object.entries(alloc);
  if (allocEntries.length === 0) {
    text("Budget allocation data not available — run AI Optimization for full breakdown.", M, y, { size: 10, color: GREY });
    nl(8);
  } else {
    const total = allocEntries.reduce((s, [, v]) => s + v, 0);
    allocEntries.forEach(([key, val]) => {
      checkPage(10);
      const pct = total > 0 ? (val / total) * 100 : 0;
      const barW = (INNER - 70) * (pct / 100);
      text(key.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase()), M, y + 4, { size: 9, color: DARK });
      fillRect(M + 70, y, barW, 6, GREEN);
      fillRect(M + 70 + barW, y, INNER - 70 - barW, 6, [240, 240, 245]);
      text(`₹${val}Cr (${pct.toFixed(1)}%)`, W - M - 2, y + 4, { size: 8, color: GREY, align: "right" });
      y += 10;
    });
  }

  nl(6);
  hline(y);
  nl(8);

  // recommendations
  text("CITY-LEVEL RECOMMENDATIONS", M, y, { size: 9, color: DARK, bold: true });
  nl(8);

  const recs = [
    { level: "extreme", text: "Deploy emergency misting stations and 24/7 cooling shelters in all extreme-risk zones immediately." },
    { level: "high",    text: "Initiate cool roof retrofitting programme across high-density built-up zones within 60 days." },
    { level: "moderate",text: "Expand tree canopy corridors along arterial roads — target 2 km of new canopy per quarter." },
    { level: "safe",    text: "Monitor safe zones quarterly; redirect budget savings to extreme-risk interventions." },
    { level: "all",     text: `Prioritise water retention infrastructure in the top ${Math.min(3, stats?.criticalZones ?? 3)} extreme zones for long-term resilience.` },
  ];

  recs.forEach(rec => {
    checkPage(14);
    const lc = LEVEL_RGB[rec.level] ?? TEAL;
    doc.setFillColor(...lc);
    doc.rect(M, y, 3, 10, "F");
    const lines = doc.splitTextToSize(rec.text, INNER - 10);
    lines.forEach((line, li) => {
      text(line, M + 7, y + 5 + li * 5, { size: 10, color: [60, 65, 80] });
    });
    y += Math.max(14, lines.length * 5 + 6);
  });

  nl(8);
  hline(y);
  nl(6);

  // footer
  text("Generated by THERMA — Urban Heat Intelligence Platform", W / 2, y + 4, { size: 8, color: GREY, align: "center" });
  text(`therma.ai  ·  ${new Date().getFullYear()}  ·  Data powered by scikit-learn Random Forest ML pipeline`, W / 2, y + 9, { size: 7, color: GREY, align: "center" });

  /* save */
  doc.save(`therma-plan-${city.toLowerCase()}-${Date.now()}.pdf`);
}
